server:
  port: 9527
spring:
  application:
    name: springcloudtest-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
      instance-id: gateway-9572.com
      prefer-ip-address: true
zuul:
  routes:
    mydept.serviceId: springcloudtest-dept
    mydept.path: /mydept/*
  #ignored-services 隐藏服务映射名
  #多个用"*" ignored-services: "*"
  ignored-services: springcloudtest-dept
  prefix: /springcloud

info:
  app.name: springcloudtest-zuul-gateway
  company.name: www.smgk.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}