server:
  port: 3344
spring:
  application:
    name: springcloud-study-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/smgk-seven/springcloudtest-config.git
          #search-paths: config-repo
          #username: 2503384157@qq.com
          #password: liu881398